In [1]:
import numpy as np 

In [11]:
# solution 1
list_=[1,2,3,4,5]
type(list_)


list

In [12]:
arr2=np.array([1,2,3,4,5])
type(arr2)

numpy.ndarray

In [13]:
##yes both have different data types 

In [14]:
## solution 2

In [15]:
for i in list_ :
    print(type(i))

for i in arr2 :
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [16]:
## solution 3 

In [17]:
array_list = np.array(object = list_, dtype = int) # redifne arrlist with dtype = int 
for i in list_ :
    print(type(i))
    
for i in array_list :
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [18]:
## solution 4

In [19]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [20]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
num_array.shape

(2, 3)

In [22]:
num_array.size

6

In [24]:
newarr = np.zeros((3,3))

In [25]:
newarr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
## solution 5 

In [27]:
identity_mat = np.eye(5)

In [28]:
identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])